export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'brand-gold': 'var(--color-brand-gold)',
        'brand-orange': 'var(--color-brand-orange)',
        primary: 'var(--color-primary)',
        'primary-pressed': 'var(--color-primary-pressed)',
        secondary: 'var(--color-secondary)',
        disabled: 'var(--color-disabled)',
        destructive: 'var(--color-destructive)',
        reward: 'var(--color-reward)',
        'reward-strong': 'var(--color-reward-strong)',
        'reward-subtle': 'var(--color-reward-subtle)',
        'reward-text': 'var(--color-reward-text)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-subtle': 'var(--color-surface-subtle)',
        'surface-selected': 'var(--color-surface-selected)',
        'surface-pressed': 'var(--color-surface-pressed)',
        'surface-inverse': 'var(--color-surface-inverse)',
        text: 'var(--color-text-primary)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-placeholder': 'var(--color-text-placeholder)',
        'text-disabled': 'var(--color-text-disabled)',
        'text-inverse': 'var(--color-text-inverse)',
        'text-brand': 'var(--color-text-brand)',
        border: 'var(--color-border)',
        'border-subtle': 'var(--color-border-subtle)',
        'border-strong': 'var(--color-border-strong)',
        'border-focused': 'var(--color-border-focused)',
        'border-error': 'var(--color-border-error)',
        success: 'var(--color-success)',
        'success-bg': 'var(--color-success-bg)',
        'success-text': 'var(--color-success-text)',
        warning: 'var(--color-warning)',
        'warning-bg': 'var(--color-warning-bg)',
        'warning-text': 'var(--color-warning-text)',
        danger: 'var(--color-danger)',
        'danger-bg': 'var(--color-danger-bg)',
        'danger-text': 'var(--color-danger-text)',
        info: 'var(--color-info)',
        'info-bg': 'var(--color-info-bg)',
        'info-text': 'var(--color-info-text)',
        scrim: 'var(--color-scrim)',
        'member-surface': 'var(--color-member-surface)',
        'member-text': 'var(--color-member-text)',
        'member-accent': 'var(--color-member-accent)',
      },
      borderRadius: {
        control: 'var(--radius-control)',
        container: 'var(--radius-container)',
        overlay: 'var(--radius-overlay)',
        pill: 'var(--radius-pill)',
        button: 'var(--radius-button)',
        card: 'var(--radius-card)',
      },
      boxShadow: {
        floating: 'var(--shadow-floating)',
        modal: 'var(--shadow-modal)',
        member: 'var(--shadow-member-card)',
        card: 'var(--shadow-card)',
      },
    },
  },
  plugins: [],
}
