import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const ctx = await browser.newContext({ viewport: { width: 375, height: 812 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
const page = await ctx.newPage()
await page.goto('https://preview.dr-card-ui.pages.dev/', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(1500)
console.log('A root -> ' + page.url())
await page.goto('https://preview.dr-card-ui.pages.dev/dearseed', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(1500)
await page.evaluate(() => { window.history.pushState({}, '', '/'); window.dispatchEvent(new PopStateEvent('popstate')) })
await page.waitForTimeout(1500)
const hasSearch = await page.evaluate(() => !!document.querySelector('input[type=search]'))
console.log('B clientnav -> ' + page.url() + ' search=' + hasSearch)
await page.goto('https://preview.dr-card-ui.pages.dev/legacy-profile/login', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(1200)
const btns = await page.$$eval('button', (els) => els.map((e) => e.textContent.trim()).slice(0, 20))
console.log('C login buttons ' + JSON.stringify(btns))
const login = page.getByRole('button', { name: '立即登录' })
if (await login.count()) { await login.first().click(); await page.waitForTimeout(3000) }
console.log('C after login -> ' + page.url())
const hasSearch2 = await page.evaluate(() => !!document.querySelector('input[type=search]'))
console.log('C search=' + hasSearch2)
await browser.close()
